# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/server-service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cql import commons_pb2 as cql_dot_commons__pb2
from cql import find_command_pb2 as cql_dot_find__command__pb2
from cql import get_command_pb2 as cql_dot_get__command__pb2
from cql import set_command_pb2 as cql_dot_set__command__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/server-service.proto',
  package='server',
  syntax='proto3',
  serialized_options=b'Z$github.com/shreybatra/crankdb/server',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bserver/server-service.proto\x12\x06server\x1a\x11\x63ql/commons.proto\x1a\x16\x63ql/find_command.proto\x1a\x15\x63ql/get_command.proto\x1a\x15\x63ql/set_command.proto2\x9e\x01\n\x07\x43rankDB\x12/\n\x03Set\x12\x0f.cql.DataPacket\x1a\x17.cql.SetCommandResponse\x12.\n\x03Get\x12\x16.cql.GetCommandRequest\x1a\x0f.cql.DataPacket\x12\x32\n\x04\x46ind\x12\x17.cql.FindCommandRequest\x1a\x0f.cql.DataPacket0\x01\x42&Z$github.com/shreybatra/crankdb/serverb\x06proto3'
  ,
  dependencies=[cql_dot_commons__pb2.DESCRIPTOR,cql_dot_find__command__pb2.DESCRIPTOR,cql_dot_get__command__pb2.DESCRIPTOR,cql_dot_set__command__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_CRANKDB = _descriptor.ServiceDescriptor(
  name='CrankDB',
  full_name='server.CrankDB',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=129,
  serialized_end=287,
  methods=[
  _descriptor.MethodDescriptor(
    name='Set',
    full_name='server.CrankDB.Set',
    index=0,
    containing_service=None,
    input_type=cql_dot_commons__pb2._DATAPACKET,
    output_type=cql_dot_set__command__pb2._SETCOMMANDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='server.CrankDB.Get',
    index=1,
    containing_service=None,
    input_type=cql_dot_get__command__pb2._GETCOMMANDREQUEST,
    output_type=cql_dot_commons__pb2._DATAPACKET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Find',
    full_name='server.CrankDB.Find',
    index=2,
    containing_service=None,
    input_type=cql_dot_find__command__pb2._FINDCOMMANDREQUEST,
    output_type=cql_dot_commons__pb2._DATAPACKET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CRANKDB)

DESCRIPTOR.services_by_name['CrankDB'] = _CRANKDB

# @@protoc_insertion_point(module_scope)
