# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cql import commons_pb2 as cql_dot_commons__pb2
from cql import find_command_pb2 as cql_dot_find__command__pb2
from cql import get_command_pb2 as cql_dot_get__command__pb2
from cql import set_command_pb2 as cql_dot_set__command__pb2


class CrankDBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Set = channel.unary_unary(
                '/server.CrankDB/Set',
                request_serializer=cql_dot_commons__pb2.DataPacket.SerializeToString,
                response_deserializer=cql_dot_set__command__pb2.SetCommandResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/server.CrankDB/Get',
                request_serializer=cql_dot_get__command__pb2.GetCommandRequest.SerializeToString,
                response_deserializer=cql_dot_commons__pb2.DataPacket.FromString,
                )
        self.Find = channel.unary_stream(
                '/server.CrankDB/Find',
                request_serializer=cql_dot_find__command__pb2.FindCommandRequest.SerializeToString,
                response_deserializer=cql_dot_commons__pb2.DataPacket.FromString,
                )


class CrankDBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Find(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrankDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=cql_dot_commons__pb2.DataPacket.FromString,
                    response_serializer=cql_dot_set__command__pb2.SetCommandResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=cql_dot_get__command__pb2.GetCommandRequest.FromString,
                    response_serializer=cql_dot_commons__pb2.DataPacket.SerializeToString,
            ),
            'Find': grpc.unary_stream_rpc_method_handler(
                    servicer.Find,
                    request_deserializer=cql_dot_find__command__pb2.FindCommandRequest.FromString,
                    response_serializer=cql_dot_commons__pb2.DataPacket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server.CrankDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CrankDB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.CrankDB/Set',
            cql_dot_commons__pb2.DataPacket.SerializeToString,
            cql_dot_set__command__pb2.SetCommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.CrankDB/Get',
            cql_dot_get__command__pb2.GetCommandRequest.SerializeToString,
            cql_dot_commons__pb2.DataPacket.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/server.CrankDB/Find',
            cql_dot_find__command__pb2.FindCommandRequest.SerializeToString,
            cql_dot_commons__pb2.DataPacket.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
