# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cql/find_command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cql/find_command.proto',
  package='cql',
  syntax='proto3',
  serialized_options=b'Z!github.com/shreybatra/crankdb/cql',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63ql/find_command.proto\x12\x03\x63ql\"#\n\x12\x46indCommandRequest\x12\r\n\x05Query\x18\x01 \x01(\x0c\x42#Z!github.com/shreybatra/crankdb/cqlb\x06proto3'
)




_FINDCOMMANDREQUEST = _descriptor.Descriptor(
  name='FindCommandRequest',
  full_name='cql.FindCommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Query', full_name='cql.FindCommandRequest.Query', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['FindCommandRequest'] = _FINDCOMMANDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FindCommandRequest = _reflection.GeneratedProtocolMessageType('FindCommandRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDCOMMANDREQUEST,
  '__module__' : 'cql.find_command_pb2'
  # @@protoc_insertion_point(class_scope:cql.FindCommandRequest)
  })
_sym_db.RegisterMessage(FindCommandRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
