# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cql/get_command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cql/get_command.proto',
  package='cql',
  syntax='proto3',
  serialized_options=b'Z!github.com/shreybatra/crankdb/cql',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63ql/get_command.proto\x12\x03\x63ql\" \n\x11GetCommandRequest\x12\x0b\n\x03key\x18\x01 \x01(\tB#Z!github.com/shreybatra/crankdb/cqlb\x06proto3'
)




_GETCOMMANDREQUEST = _descriptor.Descriptor(
  name='GetCommandRequest',
  full_name='cql.GetCommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cql.GetCommandRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['GetCommandRequest'] = _GETCOMMANDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetCommandRequest = _reflection.GeneratedProtocolMessageType('GetCommandRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCOMMANDREQUEST,
  '__module__' : 'cql.get_command_pb2'
  # @@protoc_insertion_point(class_scope:cql.GetCommandRequest)
  })
_sym_db.RegisterMessage(GetCommandRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
