# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cql/set_command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cql/set_command.proto',
  package='cql',
  syntax='proto3',
  serialized_options=b'Z!github.com/shreybatra/crankdb/cql',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63ql/set_command.proto\x12\x03\x63ql\"%\n\x12SetCommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x42#Z!github.com/shreybatra/crankdb/cqlb\x06proto3'
)




_SETCOMMANDRESPONSE = _descriptor.Descriptor(
  name='SetCommandResponse',
  full_name='cql.SetCommandResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='cql.SetCommandResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['SetCommandResponse'] = _SETCOMMANDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetCommandResponse = _reflection.GeneratedProtocolMessageType('SetCommandResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETCOMMANDRESPONSE,
  '__module__' : 'cql.set_command_pb2'
  # @@protoc_insertion_point(class_scope:cql.SetCommandResponse)
  })
_sym_db.RegisterMessage(SetCommandResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
